language: groovy
jdk:
- openjdk7
- oraclejdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"  
  - secure: yiVfOcJ1oUYEbCXIusQCmG4rur1WCRT0OoOkx1jtoBmefcU40KabcwKfRjSUZAM7IbmIeulKE11Huag0+cUV+YWbAL6/ECRTaoyXcemgMnQxKlyRK22ThYdpqJpT0Ka1kfUCB/7ZgGFHHngJzhv53OWK9Ju6oDN+polUZ5D4J+Y=
  - secure: Y88PcdoTHDj56wBJfQGktiglJniRoJRO3+uTIh6YRLDrLBbnK2dRVoP2nrd3nIble1/NRi38rqDpTc7zPAiGqdG+cjkO4tYRr+hkbNeBZSBPr/IGztkjEfPsraePyw5tssEYGqcy7jgTscIDDGqu0HO60FuLjU09yWsJ8dLabgc=
  - secure: r46Z9xpU7ltmzoA15PuOViqfUNOKLElr8n28rd3eV0ngEGDiHV6pPETa3kk+wbsC4BivBKy9UPEtS2+6BuNMxM3YV9ExgqJcL5eDpkNnK80oRp7fJgkCR8LuLbxZJ2dPE5MevEUdDwTySpWQLwCwJQh5C9LB/Qt3ECDeWh2/NHg=
